name=GroeiAcademie FrameWork
version=1.0.3
author=Alex Peeters, GROEI ACADEMIE BV
maintainer=Alex Peeters <info@groeiacademie.be>
sentence=GroeiAcademie FrameWork als Arduino-librarypakket voor de toepassingen en systemen van GROEI ACADEMIE BV.
paragraph=Bevat momenteel de toepassing Stimulus en de gedeelde Screen-laag.
category=Other
license=LGPL-3.0-or-later
url=https://groeiacademie.be/
architectures=avr,renesas_uno,esp32
depends=LiquidCrystal I2C, Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, Adafruit ADS1X15
includes=GroeiAcademie.h,Screen.h,Stimulus.h