name=GroeiAcademie
version=0.9.78
author=Alex Peeters, GROEI ACADEMIE
maintainer=GROEI ACADEMIE <info@groeiacademie.be>
sentence=Arduino-librarypakket voor de toepassingen en systemen van GROEI ACADEMIE.
paragraph=Bevat momenteel de toepassing Stimulus en de gedeelde Screen-laag.
category=Other
url=https://groeiacademie.be/
architectures=avr,renesas_uno
depends=LiquidCrystal I2C
includes=GroeiAcademie.h,Screen.h,Stimulus.h
