#ifndef EXAMPLES_CONFIG_H
#define EXAMPLES_CONFIG_H

#ifndef SERIAL_BAUDRATE
  #define SERIAL_BAUDRATE 115200UL
#endif

// Wachttijden gebruikt door de Screen-voorbeelden (Default_*Screen, Callback_*Screen).
#ifndef LEESTIJD_VOORBEELD_MS
  #define LEESTIJD_VOORBEELD_MS 2000UL
#endif
#ifndef WACHTTIJD_TUSSEN_PAGINAS_MS
  #define WACHTTIJD_TUSSEN_PAGINAS_MS 1500UL
#endif

// Aantal kanalen gebruikt door de ADC_Validatie-voorbeelden.
#ifndef STIMULUS_AANTAL_KANALEN
  #define STIMULUS_AANTAL_KANALEN 4
#endif

// doelduur van stap 3 = gemiddelde van MIN en MAX vb: MIN=3, MAX=5 → doel = 4x de nulmeting, marge dekt automatisch 3x tot 5x
#ifndef INSTORTEND_AANTAL_STAPPEN
  #define INSTORTEND_AANTAL_STAPPEN ((INSTORTEND_MINIMALE_FACTOR + INSTORTEND_MAXIMALE_FACTOR) / 2)
#endif

#ifndef MINIMALE_WACHTTIJD_MS
  #define MINIMALE_WACHTTIJD_MS 500UL
#endif
#ifndef MAXIMALE_WACHTTIJD_MS
  #define MAXIMALE_WACHTTIJD_MS 1500UL
#endif

#ifndef LCD_LEESTIJD_ENDSCORE_MS
  #define LCD_LEESTIJD_ENDSCORE_MS 5000UL
#endif
#ifndef LCD_LEESTIJD_FEEDBACK_KORT_MS
  #define LCD_LEESTIJD_FEEDBACK_KORT_MS 2000UL
#endif
#ifndef LCD_LEESTIJD_FEEDBACK_LANG_MS
  #define LCD_LEESTIJD_FEEDBACK_LANG_MS 4000UL
#endif
#ifndef LCD_LEESTIJD_MEDEDELING_KORT_MS
  #define LCD_LEESTIJD_MEDEDELING_KORT_MS 1500UL
#endif
#ifndef LCD_LEESTIJD_MEDEDELING_LANG_MS
  #define LCD_LEESTIJD_MEDEDELING_LANG_MS 3000UL
#endif

#ifndef AANTAL_SENSOREN_SIMULTAAN_2
  #define AANTAL_SENSOREN_SIMULTAAN_2 2
#endif
#ifndef AANTAL_SENSOREN_SIMULTAAN_4
  #define AANTAL_SENSOREN_SIMULTAAN_4 4
#endif

#ifndef AANTAL_SENSOREN_ALGORITME1
  #define AANTAL_SENSOREN_ALGORITME1 AANTAL_SENSOREN_SIMULTAAN_2
#endif
#ifndef AANTAL_SENSOREN_ALGORITME2
  #define AANTAL_SENSOREN_ALGORITME2 AANTAL_SENSOREN_SIMULTAAN_2
#endif
#ifndef AANTAL_SENSOREN_ALGORITME3
  #define AANTAL_SENSOREN_ALGORITME3 AANTAL_SENSOREN_SIMULTAAN_2
#endif
#ifndef AANTAL_SENSOREN_ALGORITME4
  #if AANTAL_SENSOREN_AANWEZIG == 2
    #define AANTAL_SENSOREN_ALGORITME4 AANTAL_SENSOREN_SIMULTAAN_2
  #else
    #define AANTAL_SENSOREN_ALGORITME4 AANTAL_SENSOREN_SIMULTAAN_4
  #endif
#endif

#ifndef INSTORTEND_SCORING_BINAIR
  #define INSTORTEND_SCORING_BINAIR 1
#endif
#ifndef INSTORTEND_SCORING_GRADUEEL
  #define INSTORTEND_SCORING_GRADUEEL 2
#endif

#endif
