@echo off
if /I "%~1"=="--TESTLIJST" goto :TESTLIJST

setlocal EnableDelayedExpansion
set "BESTANDSNAAM=TestLibraryNieuw"
set "CONTROLE_MODUS=INCLUDE"
set "CONTROLE_PADEN=examples\Systeem\Input\;"

call "%~dp0TestLibraryCommon.cmd" %*
exit /b %errorlevel%

:TESTLIJST
set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | MP3 21 | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario1_EnkelTik"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario2_Simultaan"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario3_Ineenstortend"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Scenario4_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED | INPUT + STIMULUS | Tik_Enkele_Samen_Instortend_Cocktail"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | TinyIRReceiver | DEFINE | D12 | DEBUG"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DDEBUG"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="HX1838 | IRremote | DEFINE | D12 | DEBUG"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DDEBUG"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="PCF8574 + HX1838 | TinyIRReceiver | DEFINE | D12"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=6 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set TEST_NAAM="PCF8574 + HX1838 | IRremote | DEFINE | D12"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=6 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set TEST_TYPE="NIEUW"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
set WELKE_FQBN_INCOMPATIBLE="arduino:zephyr:unoq"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

goto :eof

exit /b 0
