@echo off
setlocal EnableDelayedExpansion

pushd "%~dp0.."

where arduino-cli >nul 2>&1
if exist "extras\LokalePaden.cmd" (
    call "extras\LokalePaden.cmd"
) else (
    where arduino-cli >nul 2>&1
    if not errorlevel 1 (
        for /f "delims=" %%P in ('where arduino-cli') do set "CLI_PATH=%%~dpnxP"
    ) else (
        echo arduino-cli niet gevonden via PATH, en extras\LokalePaden.cmd bestaat niet.
        popd
        exit /b 1
    )
)

set "FQBN=arduino:renesas_uno:minima"
set "BOARD_VERSION=BOARD_UNO_R4_MINIMA"
set /A TESTS=0
set /A OK=0
set /A FAIL=0

call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect\InputkanalenPCF8574UserDefinedDirect.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_DIRECT" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574UserDefinedMatrix\InputkanalenPCF8574UserDefinedMatrix.ino" "INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_MATRIX" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_MATRIX -DKEYPAD_GENERIEK_AANTAL_RIJEN=3 -DKEYPAD_GENERIEK_AANTAL_KOLOMMEN=3 -DKEYPAD_GENERIEK_RIJ_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2} -DKEYPAD_GENERIEK_KOLOM_PINNEN={PCF8574_PIN_P3,PCF8574_PIN_P4,PCF8574_PIN_P5} -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4},{_LABEL_OPSCHRIFT_5,LABEL_TOETS_5},{_LABEL_OPSCHRIFT_6,LABEL_TOETS_6},{_LABEL_OPSCHRIFT_7,LABEL_TOETS_7},{_LABEL_OPSCHRIFT_8,LABEL_TOETS_8},{_LABEL_OPSCHRIFT_9,LABEL_TOETS_9}}"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "INPUT_TYPE_DIGITAL | UITGEBREIDE NON-BLOCKING EVENTS" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "INPUT_TYPE_DIGITAL | UITGEBREIDE NON-BLOCKING EVENTS | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "INPUT_TYPE_PCF8574 | UITGEBREIDE NON-BLOCKING EVENTS" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "INPUT_TYPE_PCF8574 | UITGEBREIDE NON-BLOCKING EVENTS | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "AUTOMATISCHE BOARDDETECTIE | DIGITAL" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_NONE"
call :TEST "examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino" "Input DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino" "Input DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino" "Input PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino" "Input PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :TEST "examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect\InputkanalenPCF8574UserDefinedDirect.ino" "Input PCF8574 | KEYPAD_TYPE_USER_DEFINED_DIRECT" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
call :TEST "examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino" "INPUT_TYPE_HX1838 | 17 toetsen" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :TEST "examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino" "INPUT_TYPE_HX1838 | 17 toetsen | metArgumenten" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :TEST "examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino" "INPUT_TYPE_HX1838 | USER_DEFINED" "-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"

echo ============================================================
echo TestLibraryInput-v2.0.0
echo Board : %FQBN%
echo Tests : %TESTS%
echo OK    : %OK%
echo FOUT  : %FAIL%
echo ============================================================

popd
if %FAIL% GTR 0 exit /b 1
exit /b 0

:TEST
set /A TESTS+=1
set "TEST_INO=%~1"
set "TEST_NAAM=%~2"
set "TEST_FLAGS=%~3"

if not exist "%TEST_INO%" (
    echo [FOUT] TEST_INO bestaat niet: %TEST_INO%
    set /A FAIL+=1
    exit /b 0
)

for %%X in ("%TEST_INO%") do set "TEST_DIR=%%~dpX"
set "TEST_DIR=!TEST_DIR:~0,-1!"

echo ------------------------------------------------------------
echo Compileren van: %TEST_INO%
echo FQBN: %FQBN%
echo BOARD_VERSION: %BOARD_VERSION%
echo %TEST_NAAM%
"%CLI_PATH%" compile --jobs 1 --fqbn "%FQBN%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG %TEST_FLAGS% -DBOARD_VERSION=%BOARD_VERSION%" "!TEST_DIR!"
if errorlevel 1 (
    echo [FOUT] %TEST_NAAM%
    set /A FAIL+=1
) else (
    echo [OK] %TEST_NAAM%
    set /A OK+=1
)
exit /b 0
