@echo off
cls
if exist "%~dp0TestLibraryStatusReport.txt" del /q "%~dp0TestLibraryStatusReport.txt" >nul 2>&1
:: Controleer of het script al via PowerShell met logging draait.
if "%~1"=="--logged" goto :MAIN_SCRIPT

:: Start het script opnieuw op, toon de uitvoer én bewaar het afzonderlijke logbestand.
:: De exitcode van de interne run wordt expliciet teruggegeven aan de aanroeper.
if exist "%~dp0TestLibraryNieuw.txt" del /q "%~dp0TestLibraryNieuw.txt" >nul 2>&1
powershell -NoProfile -Command "& { & '%~f0' --logged %* 2>&1 | Tee-Object -FilePath '%~dp0TestLibraryNieuw.txt'; exit $LASTEXITCODE }"
set "SCRIPT_RESULT=%errorlevel%"
exit /b %SCRIPT_RESULT%

:MAIN_SCRIPT
setlocal enabledelayedexpansion
pushd "%~dp0.."

:: Zoek arduino-cli via PATH; anders via extras\LokalePaden.cmd.
where arduino-cli >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%P in ('where arduino-cli') do set "CLI_PATH=%%~dpnP"
) else if exist "extras\LokalePaden.cmd" (
    call "extras\LokalePaden.cmd"
) else (
    echo arduino-cli niet gevonden via PATH, en extras\LokalePaden.cmd bestaat niet.
    echo Kopieer extras\LokalePaden_template.cmd naar extras\LokalePaden.cmd en vul
    echo daarin het pad naar arduino-cli in, of voeg arduino-cli toe aan PATH.
    if /I not "%~2"=="--no-pause" pause
    popd
    exit /b 1
)

:: v1.1.2: TestLibraryNieuw test de nieuwe en gewijzigde v1.1.2-functionaliteit.
:: Bestaand testconcept: nieuwe functionaliteit wordt volledig getest op alle officiële én acceptatieboards.
set "OFFICIAL_BOARDS=arduino:avr:uno arduino:renesas_uno:minima arduino:renesas_uno:unor4wifi arduino:zephyr:unoq rp2040:rp2040:cytron_maker_uno_rp2040 STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE esp32:esp32:d1_uno32 esp32:esp32:esp32s3"
set "ACCEPTANCE_BOARDS="

set /A OFFICIAL_TESTS=0
set /A OFFICIAL_OK=0
set /A OFFICIAL_FAIL=0
set /A ACCEPTANCE_TESTS=0
set /A ACCEPTANCE_OK=0
set /A ACCEPTANCE_FAIL=0
set /A STATIC_FAIL=0

findstr /C:"IRremote" library.properties >nul || (echo [FOUT] IRremote dependency ontbreekt.& set /A STATIC_FAIL+=1)
findstr /B /C:"INPUT_TYPE_HX1838	" keywords.txt >nul || (echo [FOUT] keywords.txt mist INPUT_TYPE_HX1838& set /A STATIC_FAIL+=1)

if defined ACCEPTANCE_BOARDS for %%B in (%ACCEPTANCE_BOARDS%) do call :TEST_BOARD "%%~B" ACCEPTANCE
for %%B in (%OFFICIAL_BOARDS%) do call :TEST_BOARD "%%~B" OFFICIAL

echo.
echo OFFICIEEL: !OFFICIAL_OK!/!OFFICIAL_TESTS! OK, !OFFICIAL_FAIL! FOUT
echo ACCEPTATIE: !ACCEPTANCE_OK!/!ACCEPTANCE_TESTS! OK, !ACCEPTANCE_FAIL! FOUT - GEEN RELEASE-IMPACT
echo STATISCH: !STATIC_FAIL! FOUT
set /A RELEASE_FAIL=OFFICIAL_FAIL+STATIC_FAIL

popd
echo === TEST VOLLEDIG AFGEROND ===
if /I not "%~2"=="--no-pause" (
    <nul set /p =[EINDE] Testen voltooid. Druk op een toets om af te sluiten... & pause >nul
    echo.
)
if !RELEASE_FAIL!==0 (exit /b 0) else exit /b 1

:TEST_BOARD
set "BOARD=%~1"
set "MODE=%~2"
set "BOARD_PROFIEL=%~3"
set "BOARD_FLAGS="
if "%BOARD%"=="arduino:avr:uno" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R3"
if "%BOARD%"=="arduino:renesas_uno:minima" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R4_MINIMA"
if "%BOARD%"=="arduino:renesas_uno:unor4wifi" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R4_WIFI"
if "%BOARD%"=="arduino:zephyr:unoq" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_Q"
if "%BOARD%"=="esp32:esp32:d1_uno32" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_ESP32_D1_UNO_R32"
if "%BOARD%"=="rp2040:rp2040:cytron_maker_uno_rp2040" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_RP2040_CYTRON_MAKER_UNO"
if "%BOARD%"=="STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_STM32F4_NUCLEO64_F401RE"
if "%BOARD%"=="esp32:esp32:esp32s3" (
    if not defined BOARD_PROFIEL set "BOARD_PROFIEL=BOARD_ESP32S3_ARDI32"
    set "BOARD_FLAGS=-DBOARD_VERSION=!BOARD_PROFIEL!"
)

if not defined BOARD_FLAGS (
    echo [FOUT] Geen BOARD_VERSION gekoppeld aan %BOARD%.
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
    goto :eof
)

echo ============================================================
echo INPUT-TESTS OP BOARD: %BOARD%
echo MODE=%MODE%
echo ============================================================
call :TEST_INPUT_BASIS
call :TEST_HX1838_VOLLEDIG
goto :eof

:TEST_INPUT_BASIS
set "TEST_NAAM=DIGITAL | standaard"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenDIGITAL"
set "INPUT_EXAMPLE_BESTAND=InputkanalenDIGITAL.ino"
call :COMPILE_INPUT_EXAMPLE

set "TEST_NAAM=DIGITAL | metArgumenten"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenDIGITALmetArgumenten"
set "INPUT_EXAMPLE_BESTAND=InputkanalenDIGITALmetArgumenten.ino"
call :COMPILE_INPUT_EXAMPLE

set "TEST_NAAM=PCF8574 | standaard"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenPCF8574"
set "INPUT_EXAMPLE_BESTAND=InputkanalenPCF8574.ino"
call :COMPILE_INPUT_EXAMPLE

set "TEST_NAAM=PCF8574 | metArgumenten"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenPCF8574metArgumenten"
set "INPUT_EXAMPLE_BESTAND=InputkanalenPCF8574metArgumenten.ino"
call :COMPILE_INPUT_EXAMPLE

set "TEST_NAAM=PCF8574 | UserDefinedDirect"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect"
set "INPUT_EXAMPLE_BESTAND=InputkanalenPCF8574UserDefinedDirect.ino"
call :COMPILE_INPUT_EXAMPLE

set "TEST_NAAM=PCF8574 | UserDefinedMatrix"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_MATRIX -DKEYPAD_GENERIEK_AANTAL_RIJEN=3 -DKEYPAD_GENERIEK_AANTAL_KOLOMMEN=3 -DKEYPAD_GENERIEK_RIJ_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2} -DKEYPAD_GENERIEK_KOLOM_PINNEN={PCF8574_PIN_P3,PCF8574_PIN_P4,PCF8574_PIN_P5} -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4},{_LABEL_OPSCHRIFT_5,LABEL_TOETS_5},{_LABEL_OPSCHRIFT_6,LABEL_TOETS_6},{_LABEL_OPSCHRIFT_7,LABEL_TOETS_7},{_LABEL_OPSCHRIFT_8,LABEL_TOETS_8},{_LABEL_OPSCHRIFT_9,LABEL_TOETS_9}}"
set "INPUT_EXAMPLE_DIR=examples\Systeem\Input\InputkanalenPCF8574UserDefinedMatrix"
set "INPUT_EXAMPLE_BESTAND=InputkanalenPCF8574UserDefinedMatrix.ino"
call :COMPILE_INPUT_EXAMPLE
goto :eof

:COMPILE_INPUT_EXAMPLE
if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
echo ------------------------------------------------------------
echo Compileren van: !INPUT_EXAMPLE_DIR!\!INPUT_EXAMPLE_BESTAND!
echo !TEST_NAAM!
"%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "!INPUT_EXAMPLE_DIR!" >"%TEMP%\GA_InputCompile.txt" 2>&1
set "COMPILE_RESULT=!errorlevel!"
type "%TEMP%\GA_InputCompile.txt"
if "!COMPILE_RESULT!"=="0" (
    set "GEHEUGEN_BOARD=%BOARD%"
    set "GEHEUGEN_BESTAND=!INPUT_EXAMPLE_BESTAND!"
    set "GEHEUGEN_TEST=!TEST_NAAM!"
    set "GEHEUGEN_STATUS=OK"
    call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_InputCompile.txt"
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
) else (
    echo [FOUT][%MODE%] %BOARD% ^| !TEST_NAAM!
    echo ------------------------------------------------------------
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
)
del "%TEMP%\GA_InputCompile.txt" >nul 2>&1
goto :eof

:TEST_HX1838_VOLLEDIG
set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | TinyIRReceiver | DEFINE | D12 | OK BOVENAAN 17"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HX1838
if "%BOARD%"=="arduino:zephyr:unoq" if not "!TEST_FLAGS:HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0=!"=="!TEST_FLAGS!" goto :eof
call :COMPILE_HX1838_STIMULUS_TESTS
if "%BOARD%"=="arduino:zephyr:unoq" if not "!TEST_FLAGS:HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0=!"=="!TEST_FLAGS!" goto :eof

set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | TinyIRReceiver | DEFINE | D12 | OK ONDERAAN 17"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | TinyIRReceiver | DEFINE | D12 | MP3 21"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=HX1838 | TinyIRReceiver | DEFINE | D12 | REMOTE USER DEFINED"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | IRremote | DEFINE | D12 | OK BOVENAAN 17"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | IRremote | DEFINE | D12 | OK ONDERAAN 17"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=1"
set "TEST_NAAM=HX1838 | IRremote | DEFINE | D12 | MP3 21"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=HX1838 | IRremote | DEFINE | D12 | REMOTE USER DEFINED"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
call :COMPILE_HX1838
call :COMPILE_HX1838_STIMULUS_TESTS

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=HX1838 | TinyIRReceiver | DEFINE | D12 | DEBUG"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DDEBUG"
call :COMPILE_HX1838

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=HX1838 | IRremote | DEFINE | D12 | DEBUG"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DDEBUG"
call :COMPILE_HX1838

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=PCF8574 + HX1838 | TinyIRReceiver | DEFINE | D12"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=6 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=1 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HX1838

set "TEST_MET_ARGUMENTEN=0"
set "TEST_NAAM=PCF8574 + HX1838 | IRremote | DEFINE | D12"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=6 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_ONTVANGER_PIN=ARDUINO_UNO_SHIELD_PIN_D12 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HX1838

goto :eof

:COMPILE_HX1838
set "EXAMPLE=examples\Systeem\Input\InputkanalenHX1838"
set "GEHEUGEN_EXAMPLE_BESTAND=InputkanalenHX1838.ino"
if not "!TEST_FLAGS:HX1838_TOETSENINDELING_REMOTE_USER_DEFINED=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenHX1838UserDefined"
    set "GEHEUGEN_EXAMPLE_BESTAND=InputkanalenHX1838UserDefined.ino"
)
if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
echo ------------------------------------------------------------
echo Compileren van: !EXAMPLE!\!GEHEUGEN_EXAMPLE_BESTAND!
echo !TEST_NAAM!
"%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "!EXAMPLE!" >"%TEMP%\GA_HX1838Compile.txt" 2>&1
set "COMPILE_RESULT=!errorlevel!"
type "%TEMP%\GA_HX1838Compile.txt"
if "!COMPILE_RESULT!"=="0" (
    set "GEHEUGEN_BOARD=%BOARD%"
    set "GEHEUGEN_BESTAND=!GEHEUGEN_EXAMPLE_BESTAND!"
    set "GEHEUGEN_TEST=!TEST_NAAM!"
    set "GEHEUGEN_STATUS=OK"
    call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_HX1838Compile.txt"
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
) else (
    echo [FOUT][%MODE%] %BOARD% ^| !TEST_NAAM!
    echo ------------------------------------------------------------
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
)
del "%TEMP%\GA_HX1838Compile.txt" >nul 2>&1

if "!TEST_MET_ARGUMENTEN!"=="1" (
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
    echo ------------------------------------------------------------
    echo Compileren van: examples\Systeem\Input\InputkanalenHX1838metArgumenten\InputkanalenHX1838metArgumenten.ino
    echo !TEST_NAAM! ^| metArgumenten
    "%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "examples\Systeem\Input\InputkanalenHX1838metArgumenten" >"%TEMP%\GA_HX1838CompileMetArgumenten.txt" 2>&1
    set "COMPILE_RESULT=!errorlevel!"
    type "%TEMP%\GA_HX1838CompileMetArgumenten.txt"
    if "!COMPILE_RESULT!"=="0" (
        set "GEHEUGEN_BOARD=%BOARD%"
        set "GEHEUGEN_BESTAND=InputkanalenHX1838metArgumenten.ino"
        set "GEHEUGEN_TEST=!TEST_NAAM! | metArgumenten"
        set "GEHEUGEN_STATUS=OK"
        call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_HX1838CompileMetArgumenten.txt"
        if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
    ) else (
        echo [FOUT][%MODE%] %BOARD% ^| !TEST_NAAM! ^| metArgumenten
        echo ------------------------------------------------------------
        if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
    )
    del "%TEMP%\GA_HX1838CompileMetArgumenten.txt" >nul 2>&1
)
goto :eof

:COMPILE_HX1838_STIMULUS_TESTS
for %%E in (examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail) do (
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
    set "STIM_TEST_NAAM=!TEST_NAAM! | INPUT + STIMULUS | %%~nxE"
    echo ------------------------------------------------------------
    echo Compileren van: %%E\%%~nxE.ino
    echo !STIM_TEST_NAAM!
    "%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "%%E" >"%TEMP%\GA_HX1838StimulusCompile.txt" 2>&1
    set "COMPILE_RESULT=!errorlevel!"
    type "%TEMP%\GA_HX1838StimulusCompile.txt"
    if "!COMPILE_RESULT!"=="0" (
        set "GEHEUGEN_BOARD=%BOARD%"
        set "GEHEUGEN_BESTAND=%%~nxE.ino"
        set "GEHEUGEN_TEST=!STIM_TEST_NAAM!"
        set "GEHEUGEN_STATUS=OK"
        call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_HX1838StimulusCompile.txt"
        if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
    ) else (
        echo [FOUT][%MODE%] %BOARD% ^| !STIM_TEST_NAAM!
        echo ------------------------------------------------------------
        if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
    )
)
del "%TEMP%\GA_HX1838StimulusCompile.txt" >nul 2>&1
goto :eof

:REGISTREER_GEHEUGENGEBRUIK
set "PROGRAM_USED="
set "PROGRAM_PERCENT="
set "PROGRAM_MAX="
set "RAM_USED="
set "RAM_PERCENT="
set "RAM_MAX="
for /f "tokens=3,5,12" %%A in ('findstr /B /C:"Sketch uses " "%~1"') do (
  set "PROGRAM_USED=%%A"
  set "PROGRAM_PERCENT=%%B"
  set "PROGRAM_MAX=%%C"
)
for /f "tokens=4,6,18" %%A in ('findstr /B /C:"Global variables use " "%~1"') do (
  set "RAM_USED=%%A"
  set "RAM_PERCENT=%%B"
  set "RAM_MAX=%%C"
)
set "PROGRAMMA_WEERGAVE=NIET_GEVONDEN"
set "RAM_WEERGAVE=NIET_GEVONDEN"
if defined PROGRAM_USED if defined PROGRAM_MAX set "PROGRAMMA_WEERGAVE=!PROGRAM_USED!/!PROGRAM_MAX! !PROGRAM_PERCENT!"
if defined RAM_USED if defined RAM_MAX set "RAM_WEERGAVE=!RAM_USED!/!RAM_MAX! !RAM_PERCENT!"
echo [GEHEUGEN] Board=!GEHEUGEN_BOARD! ^| Bestand=!GEHEUGEN_BESTAND! ^| Test=!GEHEUGEN_TEST! ^| Programma=!PROGRAMMA_WEERGAVE! ^| RAM=!RAM_WEERGAVE! ^| Status=!GEHEUGEN_STATUS!
goto :eof
