@echo off
cls
if exist "%~dp0TestLibraryStatusReport.txt" del /q "%~dp0TestLibraryStatusReport.txt" >nul 2>&1
:: Controleer of het script al via PowerShell met logging draait.
if "%~1"=="--logged" goto :MAIN_SCRIPT

:: Start het script opnieuw op, toon de uitvoer én bewaar het afzonderlijke logbestand.
:: De exitcode van de interne run wordt expliciet teruggegeven aan de aanroeper.
if exist "%~dp0TestLibraryNieuw.txt" del /q "%~dp0TestLibraryNieuw.txt" >nul 2>&1
powershell -NoProfile -Command "& { & '%~f0' --logged %* 2>&1 | Tee-Object -FilePath '%~dp0TestLibraryNieuw.txt'; exit $LASTEXITCODE }"
set "SCRIPT_RESULT=%errorlevel%"
exit /b %SCRIPT_RESULT%

:MAIN_SCRIPT
setlocal enabledelayedexpansion
pushd "%~dp0.."
:: Bepaal welk pad bestaat
:: Zoek arduino-cli via PATH; anders via extras\LokalePaden.cmd (lokaal, niet gedeeld -
:: zie extras\LokalePaden_template.cmd om aan te maken). Geen paden van specifieke
:: personen/machines in dit gedeelde script.
where arduino-cli >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%P in ('where arduino-cli') do set "CLI_PATH=%%~dpnP"
) else if exist "extras\LokalePaden.cmd" (
    call "extras\LokalePaden.cmd"
) else (
    echo arduino-cli niet gevonden via PATH, en extras\LokalePaden.cmd bestaat niet.
    echo Kopieer extras\LokalePaden_template.cmd naar extras\LokalePaden.cmd en vul
    echo daarin het pad naar arduino-cli in, of voeg arduino-cli toe aan PATH.
        if /I not "%~2"=="--no-pause" pause
        exit /b 1
)



set "INPUT_STIMULUS_TESTS=examples\Systeem\Input\Input_Test_Scenario1_EnkelTik examples\Systeem\Input\Input_Test_Scenario2_Simultaan examples\Systeem\Input\Input_Test_Scenario3_Ineenstortend examples\Systeem\Input\Input_Test_Scenario4_Cocktail examples\Systeem\Input\Input_Test_Tik_Enkele_Samen_Instortend_Cocktail"
set ACCEPTANCE_BOARDS="rp2040:rp2040:cytron_maker_uno_rp2040" "STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE" "esp32:esp32:esp32s3"
set "OFFICIAL_BOARDS=arduino:avr:uno arduino:renesas_uno:minima arduino:renesas_uno:unor4wifi esp32:esp32:d1_uno32"
set /A OFFICIAL_TESTS=0
set /A OFFICIAL_OK=0
set /A OFFICIAL_FAIL=0
set /A ACCEPTANCE_TESTS=0
set /A ACCEPTANCE_OK=0
set /A ACCEPTANCE_FAIL=0
set /A STATIC_FAIL=0
findstr /C:"PCF8574" library.properties >nul || (echo [FOUT] PCF8574 dependency ontbreekt in library.properties.& set /A STATIC_FAIL+=1)
findstr /C:"IRremote" library.properties >nul || (echo [FOUT] IRremote dependency ontbreekt.& set /A STATIC_FAIL+=1)
powershell -NoProfile -Command "Select-String -Path 'src\Systeem\Input\Input.cpp' -Pattern 'PrintToScreen\(\x22','Serial\.print\(\x22','Serial\.println\(\x22' | Where-Object { $_.Line -notmatch 'Serial\.(?:print|println)\(\x22\s*\x22\)' } | ForEach-Object { '{0}:{1}' -f $_.LineNumber,$_.Line }" >"%TEMP%\GA_InputHardcoded.txt"
set "HARDCODED_SIZE=0"
for %%A in ("%TEMP%\GA_InputHardcoded.txt") do set "HARDCODED_SIZE=%%~zA"
if !HARDCODED_SIZE! GTR 0 (
  echo [FOUT] Hardcoded gebruikerstekst gevonden in Input.cpp.
  type "%TEMP%\GA_InputHardcoded.txt"
  set /A STATIC_FAIL+=1
) else (
  echo [OK] Geen hardcoded gebruikerstekst in Input.cpp.
)
del "%TEMP%\GA_InputHardcoded.txt" >nul 2>&1
for %%K in (InputConfigureren OpvragenHuidigeToetsAanslag OpvragenHuidigeToetsAanslagen OpzoekenUitTeVoerenFunctieViaOpschriftToetsAanslag InputResultaat InputResultaten InputKanaal StatusOpvragenToetsAanslagen MAX_AANTAL_SIMULTANE_TOETSAANSLAGEN INPUT_TYPE_DIGITAL INPUT_TYPE_PCF8574 INPUT_TYPE_HX1838) do (
  findstr /B /C:"%%K	" keywords.txt >nul || (echo [FOUT] keywords.txt mist %%K& set /A STATIC_FAIL+=1)
)
for %%B in (%ACCEPTANCE_BOARDS%) do call :TEST_BOARD "%%~B" ACCEPTANCE
for %%B in (%OFFICIAL_BOARDS%) do call :TEST_BOARD "%%~B" OFFICIAL
echo OFFICIEEL: !OFFICIAL_OK!/!OFFICIAL_TESTS! OK, !OFFICIAL_FAIL! FOUT
echo ACCEPTATIE: !ACCEPTANCE_OK!/!ACCEPTANCE_TESTS! OK, !ACCEPTANCE_FAIL! FOUT - GEEN RELEASE-IMPACT
echo STATISCH: !STATIC_FAIL! FOUT
set /A RELEASE_FAIL=OFFICIAL_FAIL+STATIC_FAIL
popd
echo === TEST VOLLEDIG AFGEROND ===
if /I not "%~2"=="--no-pause" (
    <nul set /p =[EINDE] Testen voltooid. Druk op een toets om af te sluiten... & pause >nul
    echo.
)
if !RELEASE_FAIL!==0 (exit /b 0) else exit /b 1

:TEST_BOARD
set "BOARD=%~1"
set "MODE=%~2"
set "BOARD_FLAGS="
if "%BOARD%"=="arduino:avr:uno" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R3"
if "%BOARD%"=="arduino:renesas_uno:minima" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R4_MINIMA"
if "%BOARD%"=="arduino:renesas_uno:unor4wifi" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_UNO_R4_WIFI"
if "%BOARD%"=="esp32:esp32:d1_uno32" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_ESP32_UNO"
if "%BOARD%"=="rp2040:rp2040:cytron_maker_uno_rp2040" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_CYTRON_MAKER_UNO_RP2040"
if "%BOARD%"=="STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_NUCLEO_F401RE"
if "%BOARD%"=="esp32:esp32:esp32s3" set "BOARD_FLAGS=-DBOARD_VERSION=BOARD_ARDI32"
set "TEST_NAAM=INPUT_TYPE_NONE"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_NONE"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_DIRECT"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_MATRIX"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_MATRIX -DKEYPAD_GENERIEK_AANTAL_RIJEN=4 -DKEYPAD_GENERIEK_AANTAL_KOLOMMEN=3 -DKEYPAD_GENERIEK_RIJ_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_KOLOM_PINNEN={PCF8574_PIN_P4,PCF8574_PIN_P5,PCF8574_PIN_P6} -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4},{_LABEL_OPSCHRIFT_5,LABEL_TOETS_5},{_LABEL_OPSCHRIFT_6,LABEL_TOETS_6},{_LABEL_OPSCHRIFT_7,LABEL_TOETS_7},{_LABEL_OPSCHRIFT_8,LABEL_TOETS_8},{_LABEL_OPSCHRIFT_9,LABEL_TOETS_9},{_LABEL_OPSCHRIFT_STER,LABEL_TOETS_STER},{_LABEL_OPSCHRIFT_0,LABEL_TOETS_0},{_LABEL_OPSCHRIFT_HEKJE,LABEL_TOETS_HEKJE}}"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | IRremote | HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | IRremote | HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | IRremote | HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=0 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN | SCREEN_TYPE_SERIAL"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_SERIAL"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN | SCREEN_TYPE_SERIAL"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_SERIAL"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3 | SCREEN_TYPE_SERIAL"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3 -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_SERIAL"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | INPUT_TYPE_HX1838 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=6 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_DIGITAL | UITGEBREIDE NON-BLOCKING EVENTS"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :COMPILE_HUIDIGE_TEST
set "TEST_NAAM=INPUT_TYPE_PCF8574 | UITGEBREIDE NON-BLOCKING EVENTS"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
call :COMPILE_HUIDIGE_TEST

call :COMPILE_STIMULUS_TESTS "%BOARD%" "%MODE%"
goto :eof


:COMPILE_STIMULUS_TESTS
set "STIM_BOARD=%~1"
set "STIM_MODE=%~2"
for %%E in (%INPUT_STIMULUS_TESTS%) do (
  if "%STIM_MODE%"=="OFFICIAL" (
    set /A OFFICIAL_TESTS+=1
  ) else (
    set /A ACCEPTANCE_TESTS+=1
  )
  "%CLI_PATH%" compile --jobs 1 --fqbn "%STIM_BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG %BOARD_FLAGS%" "%%E" >"%TEMP%\GA_InputStimulusCompile.txt" 2>&1
  if errorlevel 1 (
    echo [FOUT][%STIM_MODE%] %STIM_BOARD% ^| %%~nxE
    type "%TEMP%\GA_InputStimulusCompile.txt"
    echo ------------------------------------------------------------
    if "%STIM_MODE%"=="OFFICIAL" (
      set /A OFFICIAL_FAIL+=1
    ) else (
      set /A ACCEPTANCE_FAIL+=1
    )
  ) else (
    echo [OK][%STIM_MODE%] %STIM_BOARD% ^| %%~nxE
    set "GEHEUGEN_BOARD=%STIM_BOARD%"
    for %%N in ("%%E") do set "GEHEUGEN_BESTAND=%%~nxN.ino"
    set "GEHEUGEN_TEST=INPUT_STIMULUS_TESTS"
    set "GEHEUGEN_STATUS=OK"
    call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_InputStimulusCompile.txt"
    if "%STIM_MODE%"=="OFFICIAL" (
      set /A OFFICIAL_OK+=1
    ) else (
      set /A ACCEPTANCE_OK+=1
    )
  )
)
del "%TEMP%\GA_InputStimulusCompile.txt" >nul 2>&1
goto :eof

:COMPILE_HUIDIGE_TEST
set "EXAMPLE_METARGUMENTEN="
if not "!TEST_FLAGS:INPUT_TYPE_NONE=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik"
) else if not "!TEST_FLAGS:KEYPAD_TYPE_USER_DEFINED_DIRECT=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect"
) else if not "!TEST_FLAGS:KEYPAD_TYPE_USER_DEFINED_MATRIX=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenPCF8574UserDefinedMatrix"
) else if not "!TEST_FLAGS:INPUT_TYPE_PCF8574=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenPCF8574"
    set "EXAMPLE_METARGUMENTEN=examples\Systeem\Input\InputkanalenPCF8574metArgumenten"
) else if not "!TEST_FLAGS:INPUT_TYPE_DIGITAL=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenDIGITAL"
    set "EXAMPLE_METARGUMENTEN=examples\Systeem\Input\InputkanalenDIGITALmetArgumenten"
) else if not "!TEST_FLAGS:INPUT_TYPE_HX1838=!"=="!TEST_FLAGS!" (
    set "EXAMPLE=examples\Systeem\Input\InputkanalenHX1838"
    set "EXAMPLE_METARGUMENTEN=examples\Systeem\Input\InputkanalenHX1838metArgumenten"
)
if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
"%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "%EXAMPLE%" >"%TEMP%\GA_InputCompile.txt" 2>&1
if errorlevel 1 (
  echo [FOUT][%MODE%] %BOARD% ^| !TEST_NAAM!
  type "%TEMP%\GA_InputCompile.txt"
  echo ------------------------------------------------------------
  if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
) else (
  echo [OK][%MODE%] %BOARD% ^| !TEST_NAAM!
  set "GEHEUGEN_BOARD=%BOARD%"
  for %%N in ("!EXAMPLE!") do set "GEHEUGEN_BESTAND=%%~nxN.ino"
  set "GEHEUGEN_TEST=!TEST_NAAM!"
  set "GEHEUGEN_STATUS=OK"
  call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_InputCompile.txt"
  if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
)
del "%TEMP%\GA_InputCompile.txt" >nul 2>&1

if defined EXAMPLE_METARGUMENTEN (
  if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_TESTS+=1) else set /A ACCEPTANCE_TESTS+=1
  "%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! !BOARD_FLAGS!" "%EXAMPLE_METARGUMENTEN%" >"%TEMP%\GA_InputCompileMetArgumenten.txt" 2>&1
  if errorlevel 1 (
    echo [FOUT][%MODE%] %BOARD% ^| !TEST_NAAM! ^| metArgumenten
    type "%TEMP%\GA_InputCompileMetArgumenten.txt"
    echo ------------------------------------------------------------
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_FAIL+=1) else set /A ACCEPTANCE_FAIL+=1
  ) else (
    echo [OK][%MODE%] %BOARD% ^| !TEST_NAAM! ^| metArgumenten
    set "GEHEUGEN_BOARD=%BOARD%"
    for %%N in ("!EXAMPLE_METARGUMENTEN!") do set "GEHEUGEN_BESTAND=%%~nxN.ino"
    set "GEHEUGEN_TEST=!TEST_NAAM! | metArgumenten"
    set "GEHEUGEN_STATUS=OK"
    call :REGISTREER_GEHEUGENGEBRUIK "%TEMP%\GA_InputCompileMetArgumenten.txt"
    if "%MODE%"=="OFFICIAL" (set /A OFFICIAL_OK+=1) else set /A ACCEPTANCE_OK+=1
  )
  del "%TEMP%\GA_InputCompileMetArgumenten.txt" >nul 2>&1
)
goto :eof

:REGISTREER_GEHEUGENGEBRUIK
set "PROGRAM_USED="
set "PROGRAM_PERCENT="
set "PROGRAM_MAX="
set "RAM_USED="
set "RAM_PERCENT="
set "RAM_MAX="
for /f "tokens=3,5,12" %%A in ('findstr /B /C:"Sketch uses " "%~1"') do (
  set "PROGRAM_USED=%%A"
  set "PROGRAM_PERCENT=%%B"
  set "PROGRAM_MAX=%%C"
)
for /f "tokens=4,6,18" %%A in ('findstr /B /C:"Global variables use " "%~1"') do (
  set "RAM_USED=%%A"
  set "RAM_PERCENT=%%B"
  set "RAM_MAX=%%C"
)
set "PROGRAMMA_WEERGAVE=NIET_GEVONDEN"
set "RAM_WEERGAVE=NIET_GEVONDEN"
if defined PROGRAM_USED if defined PROGRAM_MAX set "PROGRAMMA_WEERGAVE=!PROGRAM_USED!/!PROGRAM_MAX! !PROGRAM_PERCENT!"
if defined RAM_USED if defined RAM_MAX set "RAM_WEERGAVE=!RAM_USED!/!RAM_MAX! !RAM_PERCENT!"
echo [GEHEUGEN] Board=!GEHEUGEN_BOARD! ^| Bestand=!GEHEUGEN_BESTAND! ^| Test=!GEHEUGEN_TEST! ^| Programma=!PROGRAMMA_WEERGAVE! ^| RAM=!RAM_WEERGAVE! ^| Status=!GEHEUGEN_STATUS!
goto :eof
