@echo off
cls
if exist "%~dp0TestLibraryStatusReport.txt" del /q "%~dp0TestLibraryStatusReport.txt" >nul 2>&1
if "%~1"=="--logged" goto :MAIN_SCRIPT

if exist "%~dp0TestLibraryNieuwOngeldig.txt" del /q "%~dp0TestLibraryNieuwOngeldig.txt" >nul 2>&1
powershell -NoProfile -Command "& { & '%~f0' --logged %* 2>&1 | Tee-Object -FilePath '%~dp0TestLibraryNieuwOngeldig.txt'; exit $LASTEXITCODE }"
set "SCRIPT_RESULT=%errorlevel%"
exit /b %SCRIPT_RESULT%

:MAIN_SCRIPT
setlocal enabledelayedexpansion
pushd "%~dp0.."

where arduino-cli >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%P in ('where arduino-cli') do set "CLI_PATH=%%~dpnP"
) else if exist "extras\LokalePaden.cmd" (
    call "extras\LokalePaden.cmd"
) else (
    echo arduino-cli niet gevonden via PATH, en extras\LokalePaden.cmd bestaat niet.
    echo Kopieer extras\LokalePaden_template.cmd naar extras\LokalePaden.cmd en vul
    echo daarin het pad naar arduino-cli in, of voeg arduino-cli toe aan PATH.
    if /I not "%~2"=="--no-pause" pause
    popd
    exit /b 1
)

set "BOARD=arduino:renesas_uno:minima"
set /A TESTS=0
set /A OK=0
set /A FAIL=0
goto :MAIN

:EXPECT_FAIL
set /A TESTS+=1
set "EXAMPLE=examples\Systeem\Input\InputkanalenHX1838"
if not "!TEST_FLAGS:HX1838_TOETSENINDELING_REMOTE_USER_DEFINED=!"=="!TEST_FLAGS!" set "EXAMPLE=examples\Systeem\Input\InputkanalenHX1838UserDefined"
"%CLI_PATH%" compile --jobs 1 --fqbn "%BOARD%" --build-property "compiler.cpp.extra_flags=-DGROEIACADEMIE_IGNORE_USER_CONFIG !TEST_FLAGS! -DBOARD_VERSION=BOARD_UNO_R4_MINIMA" "!EXAMPLE!" >"%TEMP%\GA_HX1838Invalid.txt" 2>&1
set "COMPILE_RESULT=!errorlevel!"
if "!COMPILE_RESULT!"=="0" (
    echo [FOUT] !TEST_NAAM! compileerde onverwacht.
    set /A FAIL+=1
) else (
    findstr /C:"!VERWACHTE_FOUT!" "%TEMP%\GA_HX1838Invalid.txt" >nul
    if errorlevel 1 (
        echo [FOUT] !TEST_NAAM! faalde om een andere reden dan verwacht.
        type "%TEMP%\GA_HX1838Invalid.txt"
        set /A FAIL+=1
    ) else (
        echo [OK] !TEST_NAAM! correct geweigerd: !VERWACHTE_FOUT!
        set /A OK+=1
    )
)
del "%TEMP%\GA_HX1838Invalid.txt" >nul 2>&1
goto :eof

:MAIN
echo ============================================================
echo NIEUWE ONGELDIGE CONFIGURATIES v1.1.2: HX1838
echo ============================================================

set "TEST_NAAM=INPUT_TYPE_DIGITAL | INPUT_TYPE_HX1838"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL|INPUT_TYPE_HX1838"
set "VERWACHTE_FOUT=Geldige INPUT_KANAAL_CONFIG:"
call :EXPECT_FAIL

set "TEST_NAAM=INPUT_TYPE_DIGITAL | INPUT_TYPE_PCF8574 | INPUT_TYPE_HX1838"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL|INPUT_TYPE_PCF8574|INPUT_TYPE_HX1838"
set "VERWACHTE_FOUT=Geldige INPUT_KANAAL_CONFIG:"
call :EXPECT_FAIL

set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_BRON_CODES = 99"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=99"
set "VERWACHTE_FOUT=Ongeldige HX1838_BRON_CODES."
call :EXPECT_FAIL

set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING = 99"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=99"
set "VERWACHTE_FOUT=Ongeldige HX1838_TOETSENINDELING."
call :EXPECT_FAIL

set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE = 2"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=2"
set "VERWACHTE_FOUT=HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE moet 0 of 1 zijn."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | OK BOVENAAN 17 | HX1838_CODE_17 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DHX1838_CODE_17=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_17 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | OK ONDERAAN 17 | HX1838_CODE_17 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN -DHX1838_CODE_17=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_17 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | MP3 21 | HX1838_CODE_21 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3 -DHX1838_CODE_21=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_21 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | EEPROM_ALTIJD niet toegestaan"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_EEPROM_ALTIJD -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED wordt alleen ondersteund met HX1838_BRON_CODES_DEFINE."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | EEPROM_WANNEER_GEEN_DEFINE niet toegestaan"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_EEPROM_WANNEER_GEEN_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED wordt alleen ondersteund met HX1838_BRON_CODES_DEFINE."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal toetsen ontbreekt"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_AANTAL_TOETSEN moet ingesteld worden in UserConfig.h bij HX1838_TOETSENINDELING_REMOTE_USER_DEFINED."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | KEY_LAYOUT ontbreekt"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_KEY_LAYOUT moet ingesteld worden in UserConfig.h bij HX1838_TOETSENINDELING_REMOTE_USER_DEFINED."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal toetsen = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=0 -DHX1838_GENERIEK_CODES={0x45UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_AANTAL_TOETSEN moet tussen 1 en 255 liggen."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | codes bevatten 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x00UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_CODES mag bij HX1838_BRON_CODES_DEFINE geen code met waarde 0 bevatten."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal codes klopt niet"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_CODES moet exact HX1838_GENERIEK_AANTAL_TOETSEN codes bevatten."
call :EXPECT_FAIL

set "TEST_NAAM=HX1838 REMOTE USER DEFINED | KEY_LAYOUT lengte klopt niet"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3}}"
set "VERWACHTE_FOUT=IR_KEY_LAYOUT bevat niet het verwachte aantal HX1838-toetsen."
call :EXPECT_FAIL

echo.
echo Totaal !TESTS! - OK !OK! - FOUT !FAIL!
popd
echo === TEST VOLLEDIG AFGEROND ===
if /I not "%~2"=="--no-pause" (
    <nul set /p =[EINDE] Testen voltooid. Druk op een toets om af te sluiten... & pause >nul
    echo.
)
if !FAIL!==0 (exit /b 0) else exit /b 1
