@echo off
if /I "%~1"=="--TESTLIJST" goto :TESTLIJST

setlocal EnableDelayedExpansion
set "BESTANDSNAAM=TestLibraryNieuwOngeldig"
set "CONTROLE_MODUS=INCLUDE"
set "CONTROLE_PADEN=examples\Systeem\Input\;"
set "BRON_TEST_SCRIPT=%~dp0TestLibraryNieuw.cmd"

call "%~dp0TestLibraryCommonOngeldig.cmd" %*
exit /b %errorlevel%

:EXPECT_FAIL
set "TEST_FQBN=arduino:renesas_uno:minima"
set "TEST_BOARD_VERSION=BOARD_UNO_R4_MINIMA"
call "%~dp0TestLibraryCommonOngeldig.cmd" --VOER_DEZE_ONGELDIGE_TEST_UIT
goto :eof

:TESTLIJST
set /A TESTS=0
set /A OK=0
set /A FAIL=0

echo ============================================================
echo NIEUWE ONGELDIGE CONFIGURATIES v1.1.2: HX1838
echo ============================================================

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | INPUT_TYPE_HX1838"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL|INPUT_TYPE_HX1838"
set "VERWACHTE_FOUT=Geldige INPUT_KANAAL_CONFIG:"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | INPUT_TYPE_PCF8574 | INPUT_TYPE_HX1838"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL|INPUT_TYPE_PCF8574|INPUT_TYPE_HX1838"
set "VERWACHTE_FOUT=Geldige INPUT_KANAAL_CONFIG:"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_BRON_CODES = 99"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=99"
set "VERWACHTE_FOUT=Ongeldige HX1838_BRON_CODES."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_TOETSENINDELING = 99"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_TOETSENINDELING=99"
set "VERWACHTE_FOUT=Ongeldige HX1838_TOETSENINDELING."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=INPUT_TYPE_HX1838 | HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE = 2"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE=2"
set "VERWACHTE_FOUT=HX1838_USE_TINYIRRECEIVER_INSTEAD_OF_IRREMOTE moet 0 of 1 zijn."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | OK BOVENAAN 17 | HX1838_CODE_17 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_BOVENAAN_17_TOETSEN -DHX1838_CODE_17=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_17 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | OK ONDERAAN 17 | HX1838_CODE_17 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_OK_ONDERAAN_17_TOETSEN -DHX1838_CODE_17=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_17 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838\InputkanalenHX1838.ino"
set "TEST_NAAM=HX1838_BRON_CODES_DEFINE | MP3 21 | HX1838_CODE_21 = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_21_TOETSEN_MP3 -DHX1838_CODE_21=0"
set "VERWACHTE_FOUT=HX1838_CODE_1 t.e.m. HX1838_CODE_21 mogen bij HX1838_BRON_CODES_DEFINE niet 0 zijn."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | EEPROM_ALTIJD niet toegestaan"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_EEPROM_ALTIJD -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED wordt alleen ondersteund met HX1838_BRON_CODES_DEFINE."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | EEPROM_WANNEER_GEEN_DEFINE niet toegestaan"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_EEPROM_WANNEER_GEEN_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED wordt alleen ondersteund met HX1838_BRON_CODES_DEFINE."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal toetsen ontbreekt"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_AANTAL_TOETSEN moet ingesteld worden in UserConfig.h bij HX1838_TOETSENINDELING_REMOTE_USER_DEFINED."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | KEY_LAYOUT ontbreekt"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_KEY_LAYOUT moet ingesteld worden in UserConfig.h bij HX1838_TOETSENINDELING_REMOTE_USER_DEFINED."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal toetsen = 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=0 -DHX1838_GENERIEK_CODES={0x45UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_AANTAL_TOETSEN moet tussen 1 en 255 liggen."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | codes bevatten 0"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x00UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_CODES mag bij HX1838_BRON_CODES_DEFINE geen code met waarde 0 bevatten."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | aantal codes klopt niet"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3},{_LABEL_OPSCHRIFT_4,_LABEL_OPSCHRIFT_4}}"
set "VERWACHTE_FOUT=HX1838_GENERIEK_CODES moet exact HX1838_GENERIEK_AANTAL_TOETSEN codes bevatten."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenHX1838UserDefined\InputkanalenHX1838UserDefined.ino"
set "TEST_NAAM=HX1838 REMOTE USER DEFINED | KEY_LAYOUT lengte klopt niet"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_HX1838 -DHX1838_BRON_CODES=HX1838_BRON_CODES_DEFINE -DHX1838_TOETSENINDELING=HX1838_TOETSENINDELING_REMOTE_USER_DEFINED -DHX1838_GENERIEK_AANTAL_TOETSEN=4 -DHX1838_GENERIEK_CODES={0x45UL,0x46UL,0x47UL,0x44UL} -DHX1838_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,_LABEL_OPSCHRIFT_1},{_LABEL_OPSCHRIFT_2,_LABEL_OPSCHRIFT_2},{_LABEL_OPSCHRIFT_3,_LABEL_OPSCHRIFT_3}}"
set "VERWACHTE_FOUT=IR_KEY_LAYOUT bevat niet het verwachte aantal HX1838-toetsen."
call :EXPECT_FAIL

echo.
echo ============================================================
echo GERELEASEDE ONGELDIGE CONFIGURATIES: INPUT ZONDER HX1838
echo ============================================================

set "TEST_INO=examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | INPUT_TYPE_PCF8574"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL|INPUT_TYPE_PCF8574"
set "VERWACHTE_FOUT=Geldige INPUT_KANAAL_CONFIG:"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_KANAAL_CONFIG | ONBEKENDE INPUT-BIT"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=8"
set "VERWACHTE_FOUT=INPUT_KANAAL_CONFIG bevat een onbekend invoertype."
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE_MEMBRAAN_MATRIX_4x5=34 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5"
set "VERWACHTE_FOUT=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5 gebruikt negen signaallijnen"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set "TEST_NAAM=INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4"
set "VERWACHTE_FOUT=INPUT_TYPE_DIGITAL ondersteunt alleen KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set "TEST_NAAM=INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE_MEMBRAAN_MATRIX_4x5=34 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5"
set "VERWACHTE_FOUT=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x5 gebruikt negen signaallijnen"
call :EXPECT_FAIL

set "TEST_INO=examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set "TEST_NAAM=INPUT_TYPE_PCF8574 | SCREEN_TYPE_CHARACTER | I2C_ADDRESS_PCF8574 = I2C_ADDRESS_CHARACTER_SCREEN"
set "TEST_FLAGS=-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_CHARACTER -DI2C_ADDRESS_PCF8574=0x27 -DI2C_ADDRESS_CHARACTER_SCREEN=0x27"
set "VERWACHTE_FOUT=I2C_ADDRESS_PCF8574 mag niet gelijk zijn aan I2C_ADDRESS_CHARACTER_SCREEN."
call :EXPECT_FAIL

echo.
echo Totaal !TESTS! - OK !OK! - FOUT !FAIL!
if !FAIL!==0 (exit /b 0) else exit /b 1
