@echo off
if /I "%~1"=="--TESTLIJST" goto :TESTLIJST

setlocal EnableDelayedExpansion
set "BESTANDSNAAM=TestLibraryGereleased"
set "CONTROLE_MODUS=EXCLUDE"
set "CONTROLE_PADEN=examples\Systeem\Input\;examples\Systeem\GedeeldeBus\;"
set REGRESSIE_PADEN="examples\"

call "%~dp0TestLibraryCommon.cmd" %*
exit /b %errorlevel%

:TESTLIJST
set TEST_INO="examples\Systeem\ADC_Backend\ADC_Backend_ADS1115\ADC_Backend_ADS1115.ino"
set TEST_NAAM="ADC_BACKEND=ADC_BACKEND_ADS1115"
set TEST_FLAGS="-DADC_BACKEND=ADC_BACKEND_ADS1115"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\ADC_Backend\ADC_Backend_Native\ADC_Backend_Native.ino"
set TEST_NAAM="ADC_BACKEND=ADC_BACKEND_NATIVE"
set TEST_FLAGS="-DADC_BACKEND=ADC_BACKEND_NATIVE"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Callback_CharacterScreen\Callback_CharacterScreen.ino"
set TEST_NAAM="Callback CharacterScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Callback_PixelScreen\Callback_PixelScreen.ino"
set TEST_NAAM="Callback PixelScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Default_CharacterScreen\Default_CharacterScreen.ino"
set TEST_NAAM="CharacterScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Default_CharacterScreen_PixelScreen\Default_CharacterScreen_PixelScreen.ino"
set TEST_NAAM="Default CharacterScreen + PixelScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Default_PixelScreen\Default_PixelScreen.ino"
set TEST_NAAM="PixelScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=0"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=1"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=2"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=3"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=4"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=5"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=5"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=6"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Scenario1_EnkelTik | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=0"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=1"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=2"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=3"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=4"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=5"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=5"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=6"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario2_Simultaan\Scenario2_Simultaan.ino"
set TEST_NAAM="Scenario2_Simultaan | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=0"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=1"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=2"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=3"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=4"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=5"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=5"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=6"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario3_Ineenstortend\Scenario3_Ineenstortend.ino"
set TEST_NAAM="Scenario3_Ineenstortend | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=0"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=1"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=2"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=3"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=4"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=5"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=5"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=6"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario4_Cocktail\Scenario4_Cocktail.ino"
set TEST_NAAM="Scenario4_Cocktail | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=0"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=1"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=2"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=3"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=4"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=5"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=5"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=6"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=6"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="Tik_Enkele_Samen_Instortend_Cocktail | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="INPUT_TYPE_NONE"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_NONE"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_2x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_2x2"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_MATRIX_4x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_4x1"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_2x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x3"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_MATRIX_4x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP224_DIRECT_1x4"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_HIGH"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 | TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_TOUCH_TTP229_MATRIX_4x4 -DTTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED=TTP229_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect\InputkanalenPCF8574UserDefinedDirect.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_DIRECT"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574UserDefinedMatrix\InputkanalenPCF8574UserDefinedMatrix.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | KEYPAD_TYPE_USER_DEFINED_MATRIX"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_MATRIX -DKEYPAD_GENERIEK_AANTAL_RIJEN=3 -DKEYPAD_GENERIEK_AANTAL_KOLOMMEN=3 -DKEYPAD_GENERIEK_RIJ_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2} -DKEYPAD_GENERIEK_KOLOM_PINNEN={PCF8574_PIN_P3,PCF8574_PIN_P4,PCF8574_PIN_P5} -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4},{_LABEL_OPSCHRIFT_5,LABEL_TOETS_5},{_LABEL_OPSCHRIFT_6,LABEL_TOETS_6},{_LABEL_OPSCHRIFT_7,LABEL_TOETS_7},{_LABEL_OPSCHRIFT_8,LABEL_TOETS_8},{_LABEL_OPSCHRIFT_9,LABEL_TOETS_9}}"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | UITGEBREIDE NON-BLOCKING EVENTS"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_DIGITAL | UITGEBREIDE NON-BLOCKING EVENTS | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | UITGEBREIDE NON-BLOCKING EVENTS"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="INPUT_TYPE_PCF8574 | UITGEBREIDE NON-BLOCKING EVENTS | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 -DINPUT_KANAAL_OPVRAGEN_HUIDIGE_TOETSAANSLAG_UITGEBREID -DINPUT_KANAAL_TIMEOUT_BIJ_GEEN_TOETSAANSLAG_BINNEN_MS=1000UL"
set TEST_TYPE="GERELEASED"
set WELKE_FQBN_TESTEN="BIJ_BASIC_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="AUTOMATISCHE BOARDDETECTIE | DIGITAL"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 -DSCREEN_OUTPUT_CONFIG=SCREEN_TYPE_NONE"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Screen\Default_CharacterScreen\Default_CharacterScreen.ino"
set TEST_NAAM="CharacterScreen"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=2"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Stimulus basis | SCREEN_TYPE_NONE"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=0"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITAL\InputkanalenDIGITAL.ino"
set TEST_NAAM="Input DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenDIGITALmetArgumenten\InputkanalenDIGITALmetArgumenten.ino"
set TEST_NAAM="Input DIGITAL | KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_DIGITAL -DKEYPAD_TYPE=KEYPAD_TYPE_MEMBRAAN_DIRECT_1x4"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574\InputkanalenPCF8574.ino"
set TEST_NAAM="Input PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574metArgumenten\InputkanalenPCF8574metArgumenten.ino"
set TEST_NAAM="Input PCF8574 | KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4 | metArgumenten"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_DRUKKNOP_DIRECT_1x4"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Systeem\Input\InputkanalenPCF8574UserDefinedDirect\InputkanalenPCF8574UserDefinedDirect.ino"
set TEST_NAAM="Input PCF8574 | KEYPAD_TYPE_USER_DEFINED_DIRECT"
set TEST_FLAGS="-DINPUT_KANAAL_CONFIG=INPUT_TYPE_PCF8574 -DKEYPAD_TYPE=KEYPAD_TYPE_USER_DEFINED_DIRECT -DKEYPAD_GENERIEK_AANTAL_PINNEN=4 -DKEYPAD_GENERIEK_PINNEN={PCF8574_PIN_P0,PCF8574_PIN_P1,PCF8574_PIN_P2,PCF8574_PIN_P3} -DKEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED=KEYPAD_GENERIEK_OUTPUT_LEVEL_WHEN_KEY_PRESSED_LOW -DKEYPAD_GENERIEK_KEY_LAYOUT={{_LABEL_OPSCHRIFT_1,LABEL_TOETS_1},{_LABEL_OPSCHRIFT_2,LABEL_TOETS_2},{_LABEL_OPSCHRIFT_3,LABEL_TOETS_3},{_LABEL_OPSCHRIFT_4,LABEL_TOETS_4}}"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Scenario1_EnkelTik\Scenario1_EnkelTik.ino"
set TEST_NAAM="Input + Stimulus representatief"
set TEST_FLAGS=""
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_ALLE_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

set TEST_INO="examples\Toepassingsgebieden\Stimulus\Tik_Enkele_Samen_Instortend_Cocktail\Tik_Enkele_Samen_Instortend_Cocktail.ino"
set TEST_NAAM="UNO R3 geheugengrens | gecombineerde Stimulus | SCREEN_OUTPUT_CONFIG=7"
set TEST_FLAGS="-DSCREEN_OUTPUT_CONFIG=7"
set TEST_TYPE="REGRESSIE"
set WELKE_FQBN_TESTEN="BIJ_EXPERIMENTAL_FQBN"
call "%~dp0TestLibraryCommon.cmd" --VOER_DEZE_TEST_UIT

goto :eof

exit /b 0
